texture:
  blocks: true
  # The color of the grass/leaves depends on the colormap,
  # but still, some of their textures can never be changed.
  colormap: true
  entity: true
  environment: true
  gui: false
  items: false
  underwater: true  # color fog while player is under the water, vanilla is light blue
  map: false
  armor: false
  painting: true
  particle: false
  optfine:
    sky: true
    anim: true

whitelist:
  blocks:
    carpet: false
    ladder: false
    wood: false
    wool: false
    bed: false
    tnt: false
    glass: false
    stained_glass: false
    portal: false
    hardened_clay: false
    stained_hardened_clay: false
    water:
      flow: false
      still: true
    lava:
      flow: false
      still: false
  particle:
    footage: true
  entity:
    living: true
    armorstand: false
    arrow: true
    chest: false
    banner_base: false
    boat: false
    enchanting_table_book: false
    endercrystal: false
    experience_orb: false
    explosion: false
    lead_knot: false
    minecart: false
    sign: false

# Isolating Blocks and Items.
# For blocks where its form of the item is the block itself.
isolate: true


