texture:
  blocks: true
  # The color of the grass/leaves depends on the colormap,
  # but still, some of their textures can never be changed.
  colormap: true
  entity: false
  environment: false
  gui: false
  items: false
  map: false
  armor: false
  painting: false
  particle: false
  sky: true

whitelist:
  blocks:
    carpet: false
    ladder: true
    wood: false
    wool: true
    bed: true
    tnt: false
    glass: false
    stained_glass: false
    hardened_clay: false
    stained_hardened_clay: false
    water:
      flow: false
      still: true
    lava:
      flow: false
      still: false
  particle:
    footage: true
  entity:
    living: false
    arrow: false
    chest: false
    banner: false
    banner_base: false
    boat: false
    experience_orb: false
    explosion: false
    enchanting_table_book: true
    end_portal: true
    endercrystal: true
    sign: true
    armorstand: true

# Isolating Blocks and Items.
# For blocks where its form of the item is the block itself.
isolate: true


