# 0 ~ 1, 0 = black, 1 = gray
brightness: 0.25


# Grayscale the cover image(pack.png) or not
build_cover_image: True


texture:

  blocks: true

  # The color of the grass / leaves depends on the colormap
  # But still, some of their textures can never be changed by the resource pack
  colormap: true

  # dither effect
  effect: true

  entity: true
  environment: true
  font: false
  gui: false
  items: false

  # color fog while player is under the water, vanilla is light blue
  underwater: true

  map: false
  armor: false
  painting: true
  particle: false

  optifine:
    sky: true
    anim: true


whitelist:

  blocks:

    carpet: false
    ladder: false
    wood: true
    wool: true
    bed: true
    tnt: true
    glass: false
    stained_glass: false
    portal: false
    hardened_clay: false
    stained_hardened_clay: false

    water:
      flow: true
      still: true

    lava:
      flow: false
      still: false

  entity:

    living: true
    armorstand: false
    arrow: true
    chest: true
    banner: false
    banner_base: false
    beacon_beam: false
    boat: false
    enchanting_table_book: false
    end_portal: false
    endercrystal: false
    experience_orb: false
    explosion: false
    lead_knot: false
    minecart: false
    sign: false

  environment:

    clouds: false
    end_sky: false
    moon: false
    rain: false
    snow: false
    sun: false

  gui:

    achievement: false
    book: false
    container: false
    demo_background: false
    icons: false
    options_background: false

    # Preset world icon for new world generation
    presets: false

    # Selection arrow in resource pack menu
    resource_packs: false

    server_selection: false
    spectator_widgets: false
    stream_indicator: false

    # Include title text and background image
    title: false

    widgets: false

  particle:
    footage: true


# Isolating Blocks and Items.
# For blocks where its form of the item is the block itself.
isolate: true


